import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :s3gui, S3GuiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :s3gui, show_local_login: false

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: S3GuiData.Finch

# Do not print debug messages in production
config :logger, level: :info

config :samly, Samly.State,
  store: Samly.State.Session,
  opts: [key: :samly_assertion]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
